config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resource :registrations, only: [:new, :create]
  resource :session
  resource :dashboard, only: [:show], controller: :dashboard
  resources :passwords, param: :token

  namespace :posts do
    resource :add_post_content, only: [:create], controller: :add_post_content
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_contents, dependent: :destroy

  accepts_nested_attributes_for :post_contents
end

app/models/post_content.rb
class PostContent < ApplicationRecord
  belongs_to :post
end

# content_type
# content
# belongs to post

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :posts, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  def username
    email_address.split("@").first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to dashboard_path if authenticated?
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/posts/add_post_content_controller.rb
module Posts
  class AddPostContentController < ApplicationController
    def create
      @post = Post.new
      @content_type = params[:content_type]
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Current.user.posts
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Current.user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Current.user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Current.user.posts.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [post_contents_attributes: [[:id, :content_type, :content]]])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :require_authentication
  def new
    @user = User.new
  end

  def create
    if @user = User.create(user_params)
      start_new_session_for @user
      redirect_to root_path, notice: "User account was successfully created"
    else
      render :new
    end
  end

private

  def user_params
    params.expect(user: [:email_address, :password])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/dashboard/_post.html.erb
<div class="flex flex-col pb-8 mt-4 border-b border-gray-500" data-controller="slides">
  <div class="w-full">
    <% post.post_contents.each.with_index do |post_content, i| %>
      <div data-slides-target="slide" class="pb-4">
        <p class="text-sm mb-1"> Slide <%= i + 1 %>/<%= post.post_contents.count %> </p>
        <%= render "posts/post_contents/#{post_content.content_type}", post_content: post_content %>
      </div>
    <% end %>
  </div>

  <div class="flex gap-2 items-center">
    <%= link_to "#", data: { action: "slides#previous" } do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18" />
      </svg>
    <% end %>

    <%= link_to "#", data: { action: "slides#next" } do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
      </svg>
    <% end %>
  </div>

  <p> Posted by <%= post.user.username %> - <%= time_ago_in_words(post.created_at) %> ago </p>
</div>

app/views/dashboard/show.html.erb
<div class="w-full flex flex-col">
  <div class="w-full flex items-center justify-between"> 
    <h1 class="text-5xl"> Your Dashboard </h1>
    <div class="flex items-center gap-4"> 
      <%= link_to "New Post", new_post_path, class: "focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800" %>
    </div>
  </div>

  <div class="flex flex-col max-w-md w-full mx-auto"> 
    <%= render partial: "post", collection: @posts %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Coder Social" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= yield(:classes_for_body) %>">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<% content_for :classes_for_body, "bg-gradient-to-b from-blue-500 to-blue-300 min-h-screen overflow-hidden" %>

<div class="w-full flex flex-col items-center">
  <h1 class="font-bold text-7xl">Coder Social</h1>
  <p class="text-lg">A social platform built for coders!</p>
  <div class="flex justify-center items-center gap-4 mt-4"> 
    <%= link_to "Log in", new_session_path, class: "text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
    <%= link_to "Create Acccount", new_registrations_path, class: "text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
  </div>
</div>

<%= image_tag "coding.jpg", class: "w-[500px] h-[400px] object-cover absolute bottom-0 rotate-15" %>

<div class="w-[500px] h-[400px] object-cover absolute right-0 bottom-36 -rotate-15 bg-pink-500"> </div>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul class="list-disc ml-6">
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-full min-h-64 mt-8">
    <div class="w-full flex items-center gap-4">
      <%= link_to posts_add_post_content_path(content_type: "code"), 
        data: { turbo_method: :post },
        class: "px-3 py-2 text-sm font-medium text-center inline-flex items-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="m6.75 7.5 3 2.25-3 2.25m4.5 0h3m-9 8.25h13.5A2.25 2.25 0 0 0 21 18V6a2.25 2.25 0 0 0-2.25-2.25H5.25A2.25 2.25 0 0 0 3 6v12a2.25 2.25 0 0 0 2.25 2.25Z" />
        </svg>
        Add Code Block
      <% end %>

      <%= link_to posts_add_post_content_path(content_type: "text"), 
        data: { turbo_method: :post },
        class: "text-white bg-gradient-to-br from-purple-600 inline-flex items-center to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-3 py-2 text-center" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 0 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25" />
        </svg>
        Add Text
      <% end %>
    </div>
    
    <div id="post-contents" class="my-4 flex flex-col gap-4">
    </div>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">User:</strong>
    <%= post.user_id %>
  </div>
</div>

app/views/posts/add_post_content/create.turbo_stream.erb
<%= form_with model: @post do |f| %>
  <%= turbo_stream.append("post-contents") do %>
    <%= f.fields_for :post_contents, @post.post_contents.new,
      child_index: DateTime.now.strftime('%Q') do |pf| %>
      <% if @content_type == "code" %>
        <div class="max-w-md w-full rounded-lg bg-gray-900 min-h-64 py-2 px-4" data-controller="remove"> 
          <div class="w-full flex gap-4 items-center mb-4"> 
            <div class="w-4 h-4 rounded-full bg-gray-700"> </div>
            <div class="w-4 h-4 rounded-full bg-gray-700"> </div>
            <div class="w-4 h-4 rounded-full bg-gray-700 hover:bg-red-500" data-action="click->remove#removeWhenConfirm"> </div>
          </div>
          <%= pf.text_area :content, class: "w-full h-full text-lg text-gray-100 focus:outline-none", style: "resize:none",
            data: { controller: "autoresize", action: "autoresize#resize" } %>
          <%= pf.hidden_field :content_type, value: @content_type %>
        </div>
      <% end %>

      <% if @content_type == "text" %>
        <div class="max-w-md w-full p-2 rounded-lg min-h-64 bg-gray-700">
          <p class="text-gray-300 border-b border-gray-300 w-full mb-4"> Text Content </p>
          <%= pf.text_area :content, class: "w-full h-full text-lg text-gray-100 focus:outline-none", style: "resize:none",
            data: { controller: "autoresize", action: "autoresize#resize" } %>
          <%= pf.hidden_field :content_type, value: @content_type %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<% content_for :title, "Posts" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Posts</h1>
    <%= link_to "New post", new_post_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="posts" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render post %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", post, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_post_path(post), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="sm:inline-block">
              <%= button_to "Destroy", post, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No posts found.</p>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Back to posts", posts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/posts/post_contents/_code.html.erb
<div class="max-w-md w-full rounded-lg bg-gray-900 h-64 py-2 px-4"> 
  <div class="w-full flex gap-4 items-center mb-4"> 
    <div class="w-4 h-4 rounded-full bg-gray-700"> </div>
    <div class="w-4 h-4 rounded-full bg-gray-700"> </div>
    <div class="w-4 h-4 rounded-full bg-gray-700"> </div>
  </div>
  <p class="text-lg text-gray-100 whitespace-pre-wrap"> <%= post_content.content %> </p>
</div>

app/views/posts/post_contents/_text.html.erb
<div class="max-w-md w-full p-2 rounded-lg min-h-64 bg-gray-700">
  <p class="text-gray-300 border-b border-gray-300 w-full mb-4"> Text Content </p>
  <p class="text-lg text-gray-100 whitespace-pre-wrap"> <%= post_content.content %> </p>
</div>

app/views/posts/show.html.erb
<% content_for :title, "Showing post" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing post</h1>

  <% @post.post_contents.each do |post_content| %>
    <%= render "posts/post_contents/#{post_content.content_type}", post_content: post_content %>
  <% end %>

  <%= link_to "Edit this post", edit_post_path(@post), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="sm:inline-block mt-2 sm:mt-0 sm:ml-2">
    <%= button_to "Destroy this post", @post, method: :delete, class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>